language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - TOXENV=django17-brightcove
  - TOXENV=django17
  - TOXENV=django18-brightcove
  - TOXENV=django18
  - TOXENV=django19-brightcove
  - TOXENV=django19

install:
  - pip install tox

script:
  - tox
