version: "2"
services:
  celery:
    links:
      - elasticsearch
      - postgres
      - redis
  celerybeat:
    links:
      - redis
  celeryflower:
    environment:
      VIRTUAL_HOST: flower.*
      VIRTUAL_HOST_WEIGHT: 1
    links:
      - redis
    ports:
      - 5555
  django:
    build: .
    environment:
      EXCLUDE_PORTS: 8080
      MASTER_PASSWORD: # Get from environment
      VIRTUAL_HOST: "*"
    expose:
      - 8000
      - 8080
    links:
      - elasticsearch
      - celery
      - redis
  haproxy:
    links:
      - celeryflower
      - django
    ports:
      - 8000:8000
